version: '3'
services:
  backend:
    volumes:
      - ./:/app
    build: 
      dockerfile: Dockerfile
    environment:
        DATABASE_URL: postgresql://postgres:postgres@db:5432/wallet?sslmode=disable
        PORT: 4000
    ports:
        - 4000:4000
    depends_on:
        - db
  db:
    image: postgres:13.1-alpine
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
        - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
   pgdata: