version: "3"

tasks:
    build:
        cmds:
            - go build -o "./bin/api.exe" "./cmd/api/main.go"
    run:
        cmds:
            - ./bin/api
    migrate:
        cmds:
            - go build -o "./bin/migrate.exe" "./cmd/migrate/main.go" && ./bin/migrate.exe
    build-run:
        cmds:
            - go build -o "./bin/api.exe" "./cmd/api/main.go" && ./bin/api.exe
    start:
        cmds:  
            - go run cmd/api/main.go